name: PEP8
on:
  push:
    branches: [ '*' ]

jobs:
  PEP8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python lint libraries
        run: |
          pip install autopep8

      - name: Check for showstoppers
        run: |
          autopep8 --verbose --in-place --aggressive --aggressive *.py
          autopep8 --verbose --in-place --aggressive --aggressive userbot/*.py
          autopep8 --verbose --in-place --aggressive --aggressive userbot/modules/*.py
          autopep8 --verbose --in-place --aggressive --aggressive userbot/modules/sql_helper/*.py
          autopep8 --verbose --in-place --aggressive --aggressive userbot/utils/*.py

      # commit changes
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic lint
          commit_options: '--no-verify --signoff'
          repository: .
          commit_user_name: Angga
          commit_user_email: angga@linuxmail.org
          commit_author: Angga <angga@linuxmail.org>
